/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeeapp;

import javax.swing.JOptionPane;

/**
 *
 * @author x17114357
 */
public class EmployeeGUI extends javax.swing.JFrame {
    Employee e;
    /*
     * Creates new form EmployeeGUI
     */
    public EmployeeGUI() {
        initComponents();
        rateLbl.setVisible(false);
        rateTF.setVisible(false);
        hoursLbl.setVisible(false);
        hoursTF.setVisible(false);
        salaryLbl.setVisible(false);
        salaryTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        dobLbl = new javax.swing.JLabel();
        rateLbl = new javax.swing.JLabel();
        hoursLbl = new javax.swing.JLabel();
        salaryLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        rateTF = new javax.swing.JTextField();
        dobTF = new javax.swing.JTextField();
        hoursTF = new javax.swing.JTextField();
        salaryTF = new javax.swing.JTextField();
        printBtn = new javax.swing.JButton();
        computeBtn = new javax.swing.JButton();
        FloorBtn = new javax.swing.JButton();
        managerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EmployeeLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EmployeeLbl.setText("Employee Application");

        nameLbl.setText("Name");

        idLbl.setText("Id");

        dobLbl.setText("Dob");

        rateLbl.setText("Rate");

        hoursLbl.setText("Hours");

        salaryLbl.setText("Salary");

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });

        hoursTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursTFActionPerformed(evt);
            }
        });

        printBtn.setForeground(new java.awt.Color(255, 51, 51));
        printBtn.setText("Print");
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        computeBtn.setForeground(new java.awt.Color(204, 0, 0));
        computeBtn.setText("compute pay");
        computeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBtnActionPerformed(evt);
            }
        });

        FloorBtn.setText("Floor Staff");
        FloorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FloorBtnActionPerformed(evt);
            }
        });

        managerBtn.setText("Manager ");
        managerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(printBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dobLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rateLbl)
                                .addComponent(idLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hoursLbl)
                                .addComponent(salaryLbl)))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(salaryTF)
                            .addComponent(hoursTF)
                            .addComponent(dobTF)
                            .addComponent(rateTF)
                            .addComponent(idTF)
                            .addComponent(nameTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(computeBtn, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FloorBtn)
                            .addComponent(managerBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(EmployeeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmployeeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLbl)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FloorBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rateLbl)
                    .addComponent(rateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobLbl)
                    .addComponent(dobTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hoursLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hoursTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(managerBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salaryLbl)
                    .addComponent(salaryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(printBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(computeBtn)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void hoursTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursTFActionPerformed

    private void FloorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FloorBtnActionPerformed
      rateLbl.setVisible(true);
      rateTF.setVisible(true);
      hoursLbl.setVisible(true);
      hoursTF.setVisible(true);
      salaryTF.setVisible(false);
      salaryLbl.setVisible(false);
      e =new FloorStaff();
        // TODO add your handling code here:
    }//GEN-LAST:event_FloorBtnActionPerformed

    private void managerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerBtnActionPerformed

        salaryTF.setVisible(true);
        salaryLbl.setVisible(true);
        rateLbl.setVisible(false);
        rateTF.setVisible(false);
        hoursLbl.setVisible(false);
        hoursTF.setVisible(false);
        
        e = new Manager();
        // TODO add your handling code here:
    }//GEN-LAST:event_managerBtnActionPerformed

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed
        System.out.println("in print method");
        if(e instanceof FloorStaff){
          System.out.println("test");
        String name = nameTF.getText();
        System.out.println("name tf= "+name);
        String id = idTF.getText();
        String dob = dobTF.getText();       
        double rate =Double.parseDouble(rateTF.getText());
        double hours=Double.parseDouble(hoursTF.getText());

        e.setName(name);
        e.setDob(dob);
((FloorStaff)e).setHours(hours);
((FloorStaff)e).setRate(rate);

String output = e.printDetails();
JOptionPane.showMessageDialog(null, output);
}
  if(e instanceof Manager){
String name = nameTF.getText();
String id= idTF.getText();
String dob = dobTF.getText();
double salary = Double.parseDouble(salaryTF.getText());
e.setName(name);
e.setDob(dob);
e.setId(id);
((Manager)e).setSalary(salary);
String output=e.printDetails();

JOptionPane.showMessageDialog(null,output);


    
      
      
  }   
// TODO add your handling code here:
    }//GEN-LAST:event_printBtnActionPerformed

    private void computeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBtnActionPerformed
    if(e instanceof FloorStaff){
        e.setName(nameTF.getText());
        e.setDob(dobTF.getText());
        e.setId(idTF.getText());
        ((FloorStaff)e).setHours(Double.parseDouble(hoursTF.getText()));
        ((FloorStaff)e).setRate(Double.parseDouble(rateTF.getText()));
        e.computeWPay();
        
        JOptionPane.showMessageDialog(null, ((FloorStaff)e).getWpay());
             
    }
if(e instanceof Manager){
    e.setName(nameTF.getText());
    e.setDob(dobTF.getText());
    e.setId(idTF.getText());
    ((Manager)e).setSalary(Double.parseDouble(salaryTF.getText()));
    e.computeWPay();
    JOptionPane.showMessageDialog(null,((Manager)e).getwPay());
    
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_computeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeLbl;
    private javax.swing.JButton FloorBtn;
    private javax.swing.JButton computeBtn;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTF;
    private javax.swing.JLabel hoursLbl;
    private javax.swing.JTextField hoursTF;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTF;
    private javax.swing.JButton managerBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JButton printBtn;
    private javax.swing.JLabel rateLbl;
    private javax.swing.JTextField rateTF;
    private javax.swing.JLabel salaryLbl;
    private javax.swing.JTextField salaryTF;
    // End of variables declaration//GEN-END:variables
}
